language: swift
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0
    - os: osx
      osx_image: xcode8.3
      sudo: required
    - os: osx
      osx_image: xcode9
      sudo: required
      env: SWIFT_SNAPSHOT=4.0
script: swift test

