---
- name: clone server from github, build and run on aws ubuntu instance
  hosts: ubuntu

  tasks:
  - name: clone repo from git
    git:
      repo: 'https://github.com/tamminhdao/httpServer.git'
      dest:  /home/ubuntu/swift_server
      version: logging

  - name: build the server
    command: /home/ubuntu/Swift/usr/bin/swift build
    args:
      chdir: /home/ubuntu/swift_server

  - name: change run script mode to 0755
    file:
      path: /home/ubuntu/swift_server/run.sh
      mode: 0755

  - name: run the server
    command: ./run.sh -p 5555 -d ./cob_spec/public
    args:
      chdir: /home/ubuntu/swift_server
